const quotes = [
  "The best way to predict the future is to create it.",
  "Believe you can and you're halfway there.",
  "Do what you can, with what you have, where you are.",
  "Success is not final, failure is not fatal: It is the courage to continue that counts.",
  "Don't watch the clock; do what it does. Keep going.",
  "Act as if what you do makes a difference. It does.",
  "Keep your face always toward the sunshine—and shadows will fall behind you.",
  "You are never too old to set another goal or to dream a new dream.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "Dream big and dare to fail.",
  "Turn your wounds into wisdom.",
  "Happiness is not something ready made. It comes from your own actions.",
  "The only way to do great work is to love what you do.",
  "Don’t wait. The time will never be just right.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "The journey of a thousand miles begins with one step.",
  "In the middle of every difficulty lies opportunity.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "The mind is everything. What you think you become.",
  "I am not a product of my circumstances. I am a product of my decisions.",
  "Fall seven times and stand up eight.",
  "If you want to lift yourself up, lift up someone else.",
  "You don’t have to be great to start, but you have to start to be great.",
  "The best revenge is massive success.",
  "Do one thing every day that scares you.",
  "Your time is limited, don’t waste it living someone else’s life.",
  "Strive not to be a success, but rather to be of value.",
  "An investment in knowledge pays the best interest.",
  "The harder the conflict, the greater the triumph.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Everything has beauty, but not everyone can see it.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Life is 10% what happens to us and 90% how we react to it.",
  "The secret of getting ahead is getting started.",
  "If opportunity doesn’t knock, build a door.",
  "Challenges are what make life interesting; overcoming them is what makes life meaningful.",
  "Your life does not get better by chance, it gets better by change.",
  "Success usually comes to those who are too busy to be looking for it.",
  "You miss 100% of the shots you don’t take.",
  "It always seems impossible until it’s done.",
  "Do not go where the path may lead, go instead where there is no path and leave a trail.",
  "In every day, there are 1,440 minutes. That means we have 1,440 daily opportunities to make a positive impact.",
  "Perseverance is not a long race; it is many short races one after the other.",
  "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
  "We may encounter many defeats but we must not be defeated.",
  "It is never too late to be what you might have been.",
  "To handle yourself, use your head; to handle others, use your heart.",
  "A journey is best measured in friends, rather than miles.",
  "Be yourself; everyone else is already taken.",
  "The only person you should try to be better than is the person you were yesterday.",
  "Turn your cant’s into cans and your dreams into plans.",
  "Small steps in the right direction can turn out to be the biggest step of your life.",
  "The best preparation for tomorrow is doing your best today.",
  "Don’t count the days, make the days count.",
  "Be kind whenever possible. It is always possible.",
  "A goal is not always meant to be reached; it often serves simply as something to aim at.",
  "Courage is resistance to fear, mastery of fear, not absence of fear.",
  "Keep going. Be all in.",
  "Your passion is waiting for your courage to catch up.",
  "You are confined only by the walls you build yourself.",
  "The expert in anything was once a beginner.",
  "Great things never come from comfort zones.",
  "Push yourself, because no one else is going to do it for you.",
  "Sometimes later becomes never. Do it now.",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",
  "Everything you can imagine is real.",
  "What we achieve inwardly will change outer reality.",
  "The harder you work for something, the greater you’ll feel when you achieve it.",
  "Do not wait to strike till the iron is hot; but make it hot by striking.",
  "A smooth sea never made a skilled sailor.",
  "The future depends on what you do today.",
  "Don’t let yesterday take up too much of today.",
  "It’s not whether you get knocked down, it’s whether you get up.",
  "Opportunities don't happen, you create them.",
  "If you are not willing to risk the usual, you will have to settle for the ordinary.",
  "Trust yourself. You know more than you think you do.",
  "Never bend your head. Always hold it high. Look the world straight in the eye.",
  "You can’t cross the sea merely by standing and staring at the water.",
  "All progress takes place outside the comfort zone.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "The best dreams happen when you’re awake.",
  "Don't let the noise of others' opinions drown out your own inner voice.",
  "Don’t be afraid to give up the good to go for the great.",
  "Your attitude, not your aptitude, will determine your altitude.",
  "Do what you love, and you’ll never work another day in your life.",
  "You are braver than you believe, stronger than you seem, and smarter than you think.",
  "Life is what happens when you’re busy making other plans.",
  "Motivation is what gets you started. Habit is what keeps you going.",
  "It is not the mountain we conquer, but ourselves.",
  "Start where you are. Use what you have. Do what you can.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "Don’t wait for opportunity. Create it.",
  "The distance between dreams and reality is called action.",
  "The only journey is the one within.",
  "Don’t be afraid to fail. Be afraid not to try.",
  "Success is not in what you have, but who you are.",
  "Life isn’t about finding yourself. Life is about creating yourself.",
  "A comfort zone is a beautiful place, but nothing ever grows there.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "Do not let what you cannot do interfere with what you can do.",
  "Energy and persistence conquer all things.",
  "Failure is the condiment that gives success its flavor.",
  "Doubt kills more dreams than failure ever will.",
  "The best view comes after the hardest climb.",
  "You don’t have to see the whole staircase, just take the first step.",
  "If you can dream it, you can do it.",
  "Do not be embarrassed by your failures, learn from them and start again."
];
let quoteGenerateBtn = document.querySelector("button");
let quoteOfDay = document.querySelector("p");

function getRandomQuotes(){
   let randomIndex = Math.floor(Math.random()*quotes.length);
   return quotes[randomIndex];
};

quoteGenerateBtn.addEventListener("click", () => {
  quoteOfDay.innerText = `"${getRandomQuotes()}"`;
});